server:
  port: 8080
  tomcat:
    threads:
      max: 200

spring:
  application:
    name: cloudsphere-netdisk

  profiles:
    active: work

  servlet:
    multipart:
      enabled: true
      max-file-size: 1500MB
      max-request-size: 1600MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

cloudsphere:
  jwt:
    secret: cloudsphere_super_secure_random_key_for_jwt_token_generation_2026
    expiration: 86400